replicaCount: 1

image:
  repository: ghcr.io/your-org/springboot-app
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets:
    - name: ghcr-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  hosts:
    - host: springboot-app.local
      paths:
        - path: /
          pathType: Prefix


resources {}
